### ISSUE TITLE
Doesn't work when execution completes.

### ISSUE THREAD

**Issue by devxpy** [kuralabs/multiexit#2]
Python's atexit is designed, so that func gets called when

> At normal program termination (for instance, if sys.exit() is called or the main module’s execution completes

But with multiexit, func only gets called on termination by a signal, not on simple module completion!

**Comment by wood-j** [comment]
> Python's atexit is designed, so that func gets called when
> 
> > At normal program termination (for instance, if sys.exit() is called or the main module’s execution completes
> 
> But with multiexit, func only gets called on termination by a signal, not on simple module completion!

it's too late but this might help you

```
multiexit.run_exitfuncs(0)  # manually stop subprocess
```
